### ISSUE TITLE
服务有时候会暂停

### ISSUE THREAD

**Issue by gwhzh21** [IKende/FastHttpApi#104]
session [::ffff:ip]:46908@5120 error HTTP [::ffff:ip]:46908 0 OnRequestHandler error Index was outside the bounds of the array.@ at BeetleX.FastHttpApi.HttpApiServer.OnHttpRequest(HttpRequest request, HttpResponse response)
at BeetleX.FastHttpApi.HttpApiServer.OnRequestHandler(PacketDecodeCompletedEventArgs e)@Index was outside the bounds of the array.
at BeetleX.FastHttpApi.HttpApiServer.OnHttpRequest(HttpRequest request, HttpResponse response)
at BeetleX.FastHttpApi.HttpApiServer.OnRequestHandler(PacketDecodeCompletedEventArgs e)

**Comment by gwhzh21** [comment]
BeetleX fast http services framework
Copyright © beetlex.io 2019-2020 email:henryfan@msn.com
ServerGC [True]
BeetleX Version [1.4.9.4]
FastHttpApi Version [1.7.8.0]

**Comment by IKende** [comment]
能输出的日志都不会引起服务关闭，如果是非法异常导致的服务关闭可以看一下目录下`__UnhandledException.txt`文件。

**Comment by gwhzh21** [comment]
好的。没有发现。我再看看先。
