### ISSUE TITLE
1.75版本突然炸裂

### ISSUE THREAD

**Issue by yintao666** [IKende/FastHttpApi#144]
[2020/8/20 18:20:43] [Error] server error accept socket process error@Attempted to divide by zero.
   at BeetleX.Dispatchs.DispatchCenter`1.Next()
   at BeetleX.TcpServer.ConnectedProcess(AcceptSocketInfo e)
   at BeetleX.TcpServer.AcceptProcess(AcceptSocketInfo e)

[2020/8/20 18:20:44] [Warring] [::ffff:39.155.37.215]:31401 receive data completed socket error Success Object reference not set to an instance of an object.@   at BeetleX.TcpServer.ReceiveCompleted(SocketAsyncEventArgs e)

**Comment by yintao666** [comment]
我看日志在之前好像就服务停掉了,请问一下这个停掉的原因我应该怎么查找呢

[2020/8/20 18:13:01] [Error] @1060 accept error 一个封锁操作被对 WSACancelBlockingCall 的调用中断。|   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.Accept()
   at BeetleX.ListenHandler.OnSyncAccept()!

**Comment by asuradoll** [comment]
表示关注 我看一下我的版本先

**Comment by asuradoll** [comment]
1.838了 无忧了

**Comment by yintao666** [comment]
谢谢 我明天升级一下

**Comment by IKende** [comment]
可单独更新一下`beetlex 1.5.3.2`，这版本支在accept error后继续偿试，不过当连续计数accept error达到一定时的情况组件还是会停止服务。

**Comment by yintao666** [comment]
好的 谢谢K哥, 我这边把beetlex更新一下,请问fastHttpApi需要更新吗?

**Comment by IKende** [comment]
直接更新beetlex即可

**Comment by yintao666** [comment]
好的,已更新发布到线上啦,谢谢K哥。
