### ISSUE TITLE
Linux下使用https访问启动几分钟后就挂了

### ISSUE THREAD

**Issue by gnsilence** [IKende/FastHttpApi#28]
[08:15:32] [Error] session [::ffff:219.145.5.89]:10579@1 error [::ffff:219.145.5.89]:10579 create session ssl error Connection reset by peer@Connection reset by peer
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at BeetleX.Buffers.PipeStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)

错误信息是这样的

**Comment by IKende** [comment]
这个异常是SSL验证的异常，连接被关闭了；这个只是连接异常，正常情况下是不影响服务运作。

**Comment by gnsilence** [comment]
这个错误后就再也访问不了https地址了，任何接口都无法使用

**Comment by IKende** [comment]
@gnsilence 
你把LogLevel设置成' Debug',在HttpConfig.json文件中
```
 "LogLevel": "Debug",
```
如果出现这情况可以看一下日志的详细内容，日志在程序的logs目录下

**Comment by IKende** [comment]
@gnsilence 如果你想本地出现这错误，可以在linux下开启SSL。然后其他电脑用socket.connect到相应的服务端口后关闭连接，服务端就会抛这个异常。我本地测试暂没出现你说的情况

**Comment by gnsilence** [comment]
> @gnsilence 如果你想本地出现这错误，可以在linux下开启SSL。然后其他电脑用socket.connect到相应的服务端口后关闭连接，服务端就会抛这个异常。我本地测试暂没出现你说的情况

好的我试试看

**Comment by IKende** [comment]
的确存在某些情况sslstream异常导致CPU暴涨的情况

**Comment by IKende** [comment]
fix 1.4.0.2

**Comment by gnsilence** [comment]
好的，我下来再试试看
