### ISSUE TITLE
性能测试时，打印大量出错信息

### ISSUE THREAD

**Issue by lordoffox** [IKende/FastHttpApi#41]
[15:46:26] [Error] session [::1]:46079@3767 error send data completed SocketError Success!@Object reference not set to an instance of an object.
   at BeetleX.TcpServer.SendCompleted(SocketAsyncEventArgs e)
[15:46:26] [Error] session [::1]:46078@3766 error [::1]:46078 send data completed process handler error Object reference not set to an instance of an object.!@Object reference not set to an instance of an object.
   at BeetleX.FastHttpApi.HttpApiServer.SendCompleted(ISession session, SocketAsyncEventArgs e)
   at BeetleX.TcpServer.SendCompleted(SocketAsyncEventArgs e)

**Comment by IKende** [comment]
这个错误数据发送成功后连接被关闭引发的异常

**Comment by lordoffox** [comment]
怎样能截获这个异常，不报错呢

**Comment by IKende** [comment]
如果你不想在console输出日志可以'mApiServer.Options.LogToConsole = false;' 或设置
`mApiServer.ServerLog`自己控制日志输出。

**Comment by lordoffox** [comment]
日志还是需要的，只是这个异常不想报错，压测客户端其实已经收到了数据

**Comment by IKende** [comment]
可以继承`HttpApiServer`重写Log方法，判断异常内容是否执行base.Log

**Comment by lordoffox** [comment]
好的，我试试看

**Comment by senioi** [comment]
> 好的，我试试看

求压测数据
