### ISSUE TITLE
异常：通常每个套接字地址(协议/网络地址/端口)只允许使用一次。

### ISSUE THREAD

**Issue by sonosun** [IKende/FastHttpApi#51]
nuget上的版本为：1.5.4.2
使用HttpApiClient访问接口，会经常报异常：通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 

怀疑是httpclient任务池没有加锁导致的。请问该如何解决，另外nuget上的版本有没有对应的源码版本。

异常信息如下：
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. 
---> BeetleX.FastHttpApi.Clients.HttpClientException: request http://192.168.1.131/ error 
通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 
---> System.Net.Sockets.SocketException: 
通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at BeetleX.Clients.AsyncTcpClient.Connect()
   --- End of inner exception stack trace ---
   at BeetleX.FastHttpApi.Clients.HttpApiProxy.Invoke(MethodInfo targetMethod, Object[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_1.AppCprType(String )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Citizen.HouseServiceAgent.Extension.HttpApiLogProxy`1.Invoke(MethodInfo targetMethod, Object[] args) in E:\Project2019\Citizen\Citizen\Citizen.HouseServiceAgent\Extension\HttpApiLogProxy.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_2.AppCprType(String )
   at Citizen.HouseServiceAgent.Service.HouseManageService.AppCprType(String type) in E:\Project2019\Citizen\Citizen\Citizen.HouseServiceAgent\Service\HouseManageService.cs:line 80
   at Citizen.Admin.API.Controllers.HouseManageController.AppCprType(String type) in E:\Project2019\Citizen\Citizen\Citizen.Admin.API\Controllers\HouseManageController.cs:line 292
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()

**Comment by nodyang** [comment]
https://github.com/IKende/HttpClients 源码

**Comment by IKende** [comment]
clients用的是连接池，创建连接的时候由.net core动太分配，可能在分配过程中存在冲突创建不了。
