### ISSUE TITLE
FastHttpApi对SSL的兼容性问题

### ISSUE THREAD

**Issue by yintao666** [IKende/FastHttpApi#55]
由于使用FastHttpApi开发好了一套成熟的后台,效率性和扩展性也得到了保障,之前由于一直没有使用SSL,这次域名和ssl下来了之后迫不及待进行了ssl配置,但是之后运行的过程中总是出现
process is terminating due to StackOverflowException异常,导致后台死掉,之后我再次通过ab测试,发现访问量稍微一多就死了,现在都不敢用ssl了....

**Comment by IKende** [comment]
提供一下系统和使用的FastHttApi的版，详细日志（可以通过logs目录下获取）

**Comment by yintao666** [comment]
好的。
系统：Windows Server 2012R2
硬件:4G双核(目前用阿里云的ECS的服务器在做开发和测试)
版本:采用的BeetleX.FastHttpApi.Hosting开启Api的方式,FastHttApi版本为:1.5.4.2
错误日志:
[2019/8/19 14:31:21] [Error] session [::ffff:52.80.40.59]:38502@15 error create session ssl authenticate callback error Authentication failed because the remote party has closed the transport stream.@Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at BeetleX.TcpServer.SslAuthenticateAsyncCallback(IAsyncResult ar)

**Comment by IKende** [comment]
这种错误是正常的，是SSL验证失败不影响服务，因为服务暴露外面有很多非ssl的请求扫的。
能否提供更多有关于process is terminating due to StackOverflowException的或其他错误信息。

**Comment by yintao666** [comment]
好的 稍等 我再去找一下,我再把ssl开启用ab跑一下,太感谢您了...

**Comment by IKende** [comment]
如果方便可以把最新的日志文件发送到`henryfan@msn.com`或`28304340@qq.com`

**Comment by yintao666** [comment]
好的.

**Comment by yintao666** [comment]
我刚才用ab测试又没报错了,今天下午是App端也在调用,然后我这边开着并发50,总数量3000进行测试...我找了日志就好像这份奇怪一点点,其他的都是我之前描述的那个错误..十分感谢您,您是我的偶像...
然后这个是ab测试的时候证书读取失败, 这个还好,不会让后台死掉...
Benchmarking cqsgkj.vip (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
SSL read failed (5) - closing connection
apr_pollset_add(): Not enough space (12)
Total of 3412 requests completed
我这边再接着测试,有新的消息我再来麻烦你您.

------------------ 原始邮件 ------------------
发件人: "Henry"<notifications@github.com>;
发送时间: 2019年8月19日(星期一) 晚上7:15
收件人: "IKende/FastHttpApi"<FastHttpApi@noreply.github.com>;
抄送: "尹涛"<837437923@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [IKende/FastHttpApi] FastHttpApi对SSL的兼容性问题 (#55)

发送

提供一下系统和使用的FastHttApi的版，详细日志（可以通过logs目录下获取）
