### ISSUE TITLE
[Error] response write data error Create buffer error, maximum number of buffer pools

### ISSUE THREAD

**Issue by Vladislav93** [IKende/FastHttpApi#79]
Hello! I get this error in my HTTP server.
`[Error] x.x.xx:42468 POST /x/x/set response write data error Create buffer error, maximum number of buffer pools!@   at BeetleX.Buffers.BufferPool.CreateBuffer()
at BeetleX.Buffers.BufferPool.Pop()
at BeetleX.Buffers.PipeStream.GetWriteBuffer()
at BeetleX.Buffers.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
at BeetleX.FastHttpApi.HttpResponse.OnWrite(PipeStream stream)
at BeetleX.FastHttpApi.HttpResponse.Write(PipeStream stream)`

Why is it happen? and what should I do to avoid it?)
thanks

**Comment by IKende** [comment]
setting  `HttpSever.Options.BufferPoolMaxMemory` default value is `100` MB
