### ISSUE TITLE
docker中编译项目.编译通过,但是访问接口时报错

### ISSUE THREAD

**Issue by wryl** [IKende/FastHttpApi#81]
[06:32:23] [Info] HTTP 26414121700294661 [::ffff:218.240.133.7]:49143 request from multi receive

[06:32:23] [Info] [::ffff:218.240.133.7]:49143 begin receive

[06:32:23] [Info] [::ffff:218.240.133.7]:49143 receive 541 length completed

[06:32:23] [Trace] [::ffff:218.240.133.7]:49143 receive hex:3225334166616c736525324325323272657065617465722532322533412537422532326175746f5265667265736825323225334166616c7365253243253232726566726573685261746525323225334125323233302532322537442537443b20706f727461696e65722e737761726d76697375616c697a65725f646973706c61795f6f6e6c795f72756e6e696e675f7461736b733d66616c73653b20706f727461696e65722e737761726d76697375616c697a65725f646973706c61795f6e6f64655f6c6162656c733d66616c73653b20706f727461696e65722e646174617461626c655f657870616e6465646974656d735f73657276696365733d2535422532326c347a706770663063686f366a7575337830326f637a63757525323225324325323272343730736f62687430366a6d3368706d337632616565787125323225324325323273766237656278736865647536733370376e78676e713467332532322535443b20706f727461696e65722e646174617461626c655f706167696e6174696f6e5f636f6e7461696e6572733d3130303b205f6769746c61625f73657373696f6e3d30366665613431313139633239323438303838326364643133363637323632663b206576656e745f66696c7465723d616c6c3b20706f727461696e65722e4c4f47494e5f53544154455f555549443d61353336336663612d376537362d346165312d623065392d3161663033393937393737620d0a0d0a

[06:32:23] [Error] session [::ffff:218.240.133.7]:49143@5 error [::ffff:218.240.133.7]:49143 session  buffer decoding error! @Specified argument was out of the range of valid values.

   at BeetleX.Buffers.Buffer.Read(Byte[] buffer, Int32 offset, Int32 count)

   at BeetleX.Buffers.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 count)

   at BeetleX.FastHttpApi.PipeStreamExtend.ReadLine(PipeStream stream, Span`1& line)

   at BeetleX.FastHttpApi.Header.Read(PipeStream stream, Cookies cookies)

   at BeetleX.FastHttpApi.HttpRequest.LoadHeaer(PipeStream stream)

   at BeetleX.FastHttpApi.HttpRequest.Read(PipeStream stream)

   at BeetleX.FastHttpApi.HttpPacket.OnHttpDecode(ISession session, PipeStream pstream)

   at BeetleX.FastHttpApi.HttpPacket.Decode(ISession session, Stream stream)

   at BeetleX.TcpServer.SessionReceive(SessionReceiveEventArgs e)

**Comment by wryl** [comment]
FROM microsoft/dotnet:2.2-sdk AS build-env

WORKDIR /app
COPY /. /app
RUN dotnet publish

FROM microsoft/dotnet:2.2-sdk
WORKDIR /app
COPY --from=build-env /app/bin/Debug/netcoreapp2.2/publish .
ENTRYPOINT [ "dotnet" ,"dotnetcore.dll" ]
这是dockerfile
编译的是官方demo

**Comment by IKende** [comment]
提供一下对应`fasthttpapi`的版本，receive data 还有部分日志没发完整，从日志看这个请求是进行了多次接收才完成。

**Comment by wryl** [comment]
版本为当前最新版,日志已经找不到了.但是确定的是用这个dockerfile是可以重现的

**Comment by IKende** [comment]
能否提供一份接收完整的请求数据日志，
因为提交给TechEmpower测试也是用同样的dockerfile
